---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-netology
  labels:
    app: netology
spec:
  replicas: 3
  selector:
    matchLabels:
      app: network
  template:
    metadata:
      labels:
        app: network
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: http-port
---
apiVersion: v1
kind: Service
metadata:
  name: network
spec:
  selector:
    app: network
  ports:
    - name: service-nging
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-nging
      protocol: TCP
      port: 9002
      targetPort: 8080