apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-netology-2
  labels:
    app: netology-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netology-2
  template:
    metadata:
      labels:
        app: netology-2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
      initContainers:
        - name: init
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - "for i in {1..100}; do sleep 10; if nslookup test-2svc; then exit 0; fi; done; exit 1"
