apiVersion: v1
kind: ConfigMap
metadata:
  name: port-multitool
data:
  port: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-page
data:
  text: |
    "Hello Netology"

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 9090
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: port-multitool
              key: port
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: config
          mountPath: "/usr/share/nginx/html/index.html"
          readOnly: true
          subPath: index.html
      volumes:
      - name: config
        configMap:
          name: web-page
          items:
          - key: text
            path: index.html

