- name: Download key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/trusted.gpg.d/kubernetes.asc
    mode: "0644"
    force: true

- name: Adding apt repository for Kubernetes
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
    state: present
    filename: kubernetes.list
    update_cache: true

- name: Install Kubernetes binaries
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Hold package at current version
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  notify: Restart kubelet
  register: kubecomponents_install_result

- name: Flush_handlers
  ansible.builtin.meta: flush_handlers
