---
- name: Iclude bootstrap
  ansible.builtin.include_tasks:
    file: bootstrap.yaml

- name: Iclude tasks swap off
  ansible.builtin.include_tasks:
    file: disable_swap.yaml

- name: Include task to configure containerd container runtime
  ansible.builtin.include_tasks:
    file: setup_containerd_debian.yaml
  when: k8s_install_container_runtime == "containerd"

- name: Iclude tasks install kubelet
  ansible.builtin.include_tasks:
    file: install_kubelet.yaml

- name: Rebooting
  ansible.builtin.reboot:
    post_reboot_delay: 60
  throttle: 5
  when: kubecomponents_install_result.changed and containerd_install_result.changed
