- name: Add containerd gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add containerd software repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker.list
    update_cache: true

- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
  notify: Restart containerd
  register: containerd_install_result

- name: Configure containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0644"

- name: Configure containerd
  ansible.builtin.command: containerd config default | tee /etc/containerd/config.toml
  notify: Restart containerd
  register: my_output
  changed_when: my_output.rc != 0

- name: Configure containerd
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: Restart containerd

- name: Flush_handlers
  ansible.builtin.meta: flush_handlers
