---
microk8s_kubectl_version_url: "https://storage.googleapis.com/kubernetes-release/release/stable.txt"

microk8s_kubectl_url: "https://storage.googleapis.com/kubernetes-release/release/{{ lookup('url', microk8s_kubectl_version_url) }}/bin/linux/amd64/kubectl"