apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-logs-describe
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-logs-describe-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-logs-describe
subjects:
- kind: User
  name: IINetology
  apiGroup: rbac.authorization.k8s.io
