---
- name: Check if kubeadm has already run
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Join control nodes
  when: not kubeadm_ca.stat.exists
  ansible.builtin.shell:
    cmd: |
      kubeadm join {{ k8s_ha_mmm_ha_cluster_virtual_ip }}:7443 \
      --token {{ hostvars[groups['k8s_masters'][0]].join_token.stdout }} \
      --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_masters'][0]].discovery_token_ca_cert_hash.stdout }} \
      --control-plane --certificate-key {{ hostvars[groups['k8s_masters'][0]].certificate_key.stdout }}
  notify: Restart kubelet
  register: my_output
  changed_when: my_output.rc != 0

# Add link

- name: Add directory for config file
  ansible.builtin.file:
    path: /home/{{ ansible_ssh_user }}/.kube
    state: directory
    mode: "0755"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  notify: Restart kubelet

- name: Add link for config file
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_ssh_user }}/.kube/config
    remote_src: true
    mode: "0644"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  notify: Restart kubelet
