---
- name: Set sysctl
  ansible.posix.sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: "1"
    sysctl_set: true
    state: present
    ignoreerrors: true

- name: Install packages
  ansible.builtin.apt:
    name:
      - keepalived
      - haproxy
  when: ansible_os_family == "Debian"
  notify:
    - Restart haproxy
    - Restart keepalived

- name: Copy keepalived.conf to master
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart keepalived

- name: Copy haproxy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    group: haproxy
    mode: '0644'
  notify: Restart haproxy

- name: Flush_handlers
  ansible.builtin.meta: flush_handlers

- name: Copy kubeadm-config.yaml
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0644'
