---
- name: Generate join token
  ansible.builtin.command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  register: kubeadm_init
  changed_when: kubeadm_init.rc != 0

- name: Add directory for config file
  ansible.builtin.file:
    path: /home/{{ ansible_ssh_user }}/.kube
    state: directory
    mode: "0755"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Add link for config file
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_ssh_user }}/.kube/config
    remote_src: true
    mode: "0644"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Install Pod network
  become: true
  become_user: "{{ ansible_ssh_user }}"
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
  register: my_output
  changed_when: my_output.rc != 0
  when: inventory_hostname == 'k8s-master1'

- name: Generate join token
  ansible.builtin.command: kubeadm token create
  register: join_token
  changed_when: join_token.rc != 0

- name: Message join_token
  ansible.builtin.debug:
    msg: "{{ join_token.stdout }}"

- name: Get discovery-token-ca-cert-hash
  ansible.builtin.shell:
     cmd: |
       openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | \
       openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: discovery_token_ca_cert_hash
  changed_when: discovery_token_ca_cert_hash.rc != 0

- name: Message discovery_token_ca_cert_hash
  ansible.builtin.debug:
    msg: "{{ discovery_token_ca_cert_hash.stdout }}"

- name: Upload certs
  ansible.builtin.shell:
    cmd: kubeadm init phase upload-certs --upload-certs | tail -1
  register: certificate_key
  changed_when: certificate_key.rc != 0

- name: Message
  ansible.builtin.debug:
    msg: "{{ certificate_key.stdout }}"

- name: Get join path
  ansible.builtin.shell: kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' | cut -c9-
  register: join_path
  changed_when: join_path.rc != 0

- name: Message
  ansible.builtin.debug:
    msg: "{{ join_path.stdout }}"
