---
- name: Install Kubernetes binaries
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - curl

- name: Install kubectl
  ansible.builtin.get_url:
    url: "{{ microk8s_kubectl_url }}"
    dest: /usr/bin/kubectl
    mode: "755"
